Fix API main function. Identation.

diff --git a/test/test_runner b/test/test_runner
--- a/test/test_runner
+++ b/test/test_runner
@@ -1,25 +1,25 @@
-#!/usr/bin/env bash
+#! /usr/bin/env bash
 #  Test runner for unit tests.
 set -euo pipefail
 IFS=$'\n\t'
 
 #  Show the help content.
 _help_test_runner() { 
-	local _content=(
-	    " Test runner for unit tests."
-		""
-		" Usage: ./test_runner <test> [--list] [--help]"
-		""
-		" Options:"
-		"   --list:  Display the <test> list. Test files must follow"
-		"              the next rules:"
-		"                1. Test filename with pattern '<name>_test'."
-		"                2. Test file in where 'test_runner' is."
-		"                3. No execution permissions are required"
-		"                   for test files."
-		"   --help:  Display this help message."
-	)
-	echo "${_content[*]}"
+    local _content=(
+        " Test runner for unit tests."
+        ""
+        " Usage: ./test_runner <test> [--list] [--help]"
+        ""
+        " Options:"
+        "   --list:  Display the <test> list. Test files must follow"
+        "              the next rules:"
+        "                1. Test filename with pattern '<name>_test'."
+        "                2. Test file in where 'test_runner' is."
+        "                3. No execution permissions are required"
+        "                   for test files."
+        "   --help:  Display this help message."
+    )
+    echo "${_content[*]}"
 }
 expr "$*" : ".*--help" > /dev/null \
     && _help_test_runner \
@@ -32,9 +32,9 @@ expr "$*" : ".*--help" > /dev/null \
 #+ directory where 'test_runner' is.
 _list_tests() {
     declare -a _tests=$( ls *_test )
-	for _test in ${_tests[@]}; do
+    for _test in ${_tests[@]}; do
         echo $( echo "$_test" | cut -d '_' -f 1 )
-	done
+    done
 }
 expr "$*" : ".*--list" > /dev/null \
     && _list_tests \
@@ -42,6 +42,7 @@ expr "$*" : ".*--list" > /dev/null \
 
 #  Assertions count.
 _assertions=0
+
 #  Failed assertions count.
 _failures=0
 
@@ -50,23 +51,30 @@ _inc_asserts() {
     _assertions=$(( _assertions+1 ))
 }
 
-#  Print the failed test message and 
+#  Print the failed test message and
 #+ increase the '_failures' count.
 _fail() {
     echo ">>>   [FAILED]   $*"
     _failures=$(( _failures+1 ))
 }
 
-#  Print the test results.
+#  Print the test results and execute
+#+ the global after-tests script.
 #  This function is called after 
 #+ execute the main code or after
 #+ get an error.
 _finally_test_runner() {
     if [ $_failures = 0 ]; then
         echo "$( basename "$0" ): [PASSED] - [$_assertions] of [$_assertions] assertions passed"
-        exit 0
     else
         echo "$( basename "$0" ): [FAILED] - [$_failures] of [$_assertions] assertions failed"
+    fi
+
+    . ./test_after_tests
+
+    if [ $_failures = 0 ]; then
+        exit 0
+    else
         exit 1
     fi
 }
@@ -78,25 +86,21 @@ _finally_test_runner() {
 #    3. Verify the kind of execution:
 #+      single test or all tests.
 #    4. Execute test(s).
-#    5. Execute the global after-tests
-#+      script.
-#    6. Finally function is executed.
+#    5. Finally function is executed.
 if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
-	trap _finally_test_runner EXIT
-	
+    trap _finally_test_runner EXIT
+
     . ./test_before_tests
     . ./test_asserts
-    
+
     readonly _single=${1:-''}
-    
+
     if [ -n "$_single" ]; then
         eval '. ./${_single}_test'
     else
         declare -a _tests=$( ls *_test )
-    	for _test in ${_tests[@]}; do
-    		eval '. ./$_test'
-    	done
+        for _test in ${_tests[@]}; do
+            eval '. ./$_test'
+        done
     fi
-    
-    . ./test_after_tests
 fi
