Nginx set-up validation.

diff --git a/test/mock/clean_mock b/test/mock/clean_mock
--- a/test/mock/clean_mock
+++ b/test/mock/clean_mock
@@ -9,7 +9,6 @@ IFS=$'\n\t'
 #+ stop service.
 nginx -v
 service nginx stop
-service nginx status
 
 
 #  Remove services files.
@@ -20,6 +19,19 @@ rm -rf "${_nginx_share}shttp_mock"
 #  Clean-up Nginx server
 readonly _nginx_available="/etc/nginx/sites-available/"
 readonly _nginx_enabled="/etc/nginx/sites-enabled/"
+readonly _mock_conf="shttp_mock.conf"
 
-rm -rf "${_nginx_available}shttp"*
-rm -rf "${_nginx_enabled}shttp"*
+rm -rf $_nginx_available$_mock_conf
+rm -rf $_nginx_enabled$_mock_conf
+
+
+#  Validate set-down
+if [ -d ${_nginx_share}shttp_mock ] \
+    || [ -f $_nginx_available$_mock_conf ] \
+    || [ -f $_nginx_enabled$_mock_conf ]; then
+    printf "\r%*s\r%s\n" "$(tput cols)" "[ FAILED ] " "setup_mock: Mock services set-down failed";
+    exit 1
+else
+    printf "\r%*s\r%s\n" "$(tput cols)" "[ OK ] " "setup_mock: Mock services correctly set-down";
+fi
+
diff --git a/test/mock/setup_mock b/test/mock/setup_mock
--- a/test/mock/setup_mock
+++ b/test/mock/setup_mock
@@ -34,18 +34,27 @@ cp $_mock_conf $_nginx_available
 #  Put correct service location
 sed -i -e "s|{{_shttp_srv_location}}|$_srv_location|g" $_nginx_available$_mock_conf
 
-cat "/etc/nginx/sites-available/default"
-
 # Clean-up last files in enabled sites
 rm -rf "${_nginx_enabled}shttp"*
 
 #  Enable site by creating a symbolic link
 ln -s $_nginx_available$_mock_conf $_nginx_enabled
 
+
+#  Check configuration and
+#+ restart service.
 nginx -t
 service nginx restart
-service nginx status
 
 
-#  Ping Nginx
-curl http://127.0.0.1
+#  Validate set-up
+readonly _nginx_ping_status=$( curl -o /dev/null \
+    -sw '%{http_code}' \
+    http://127.0.0.1:5555/info
+)
+if [ "$_nginx_ping_status" = "200" ]; then
+    printf "\r%*s\r%s\n" "$(tput cols)" "[ OK ] " "setup_mock: Mock services correctly set-up";
+else
+    printf "\r%*s\r%s\n" "$(tput cols)" "[ FAILED ] " "setup_mock: Mock services set-up failed";
+    exit 1
+fi
